<?php

namespace HomeAutomation\Worker;

class RS485Worker extends \Worker
{

    public function run()
    {
        while (true) {
            echo "5";
            sleep(2);
        }

        parent::run(); // TODO: Change the autogenerated stub
    }

}